backend:
  name: github
  repo: idaneschilling/fitness #set to your repo name

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "daily"
    label: "Daily"
    folder: 'content/daily'
    create: true
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "daily"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Daily Photo", name: "dailyPhoto", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
